"""adiciona usuarios e vincula categorias e lancamentos

Revision ID: 8e1a593eba37
Revises: 0437bafa0339
Create Date: 2026-08-03 16:59:01.743357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1a593eba37'
down_revision = '0437bafa0339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_categoria_nome_tipo'), type_='unique')
        batch_op.create_unique_constraint('uq_categoria_nome_tipo', ['usuario_id', 'nome', 'tipo'])
        batch_op.create_index(batch_op.f('ix_categorias_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_foreign_key('fk_categorias_usuario', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lancamentos_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_foreign_key('fk_lancamentos_usuario', 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lancamentos_usuario', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lancamentos_usuario_id'))
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categorias_usuario', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_categorias_usuario_id'))
        batch_op.drop_constraint('uq_categoria_nome_tipo', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_categoria_nome_tipo'), ['nome', 'tipo'])
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
