"""adiciona registro de tentativas de acesso

Revision ID: a51512c66b9b
Revises: 8e1a593eba37
Create Date: 2026-08-03 23:05:46.922213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51512c66b9b'
down_revision = '8e1a593eba37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tentativas_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('identificador', sa.String(length=180), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tentativas_acesso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tentativas_acesso_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_tentativas_acesso_identificador'), ['identificador'], unique=False)
        batch_op.create_index(batch_op.f('ix_tentativas_acesso_ip'), ['ip'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tentativas_acesso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tentativas_acesso_ip'))
        batch_op.drop_index(batch_op.f('ix_tentativas_acesso_identificador'))
        batch_op.drop_index(batch_op.f('ix_tentativas_acesso_criado_em'))

    op.drop_table('tentativas_acesso')
    # ### end Alembic commands ###
